[project]
name = "cbp_api"
version = "0.0.1"
dependencies = [
    "requests",
    "pandas",
    'importlib-metadata; python_version<"3.10"',
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
